# Generated by Django 4.0.2 on 2022-06-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_alter_person_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
