# Generated by Django 4.0.2 on 2022-06-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salary", "0005_alter_personbonusproject_bonus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "persons", "verbose_name_plural": "persons"},
        ),
        migrations.AlterField(
            model_name="personbonusproject",
            name="bonus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="salary.bonus",
            ),
        ),
    ]
