# Generated by Django 4.0.2 on 2022-06-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_alter_person_options_alter_personbonusproject_bonus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
    ]
